version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/.clusterfuzzlite"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/distrib/docker"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
